n = input('Digite algo: ')
print('O tipo digitado é um',type(n))
print('É uma string?',n.isalpha())
print('É um número?',n.isnumeric())
print('Está escrito em maiúsculo?', n.isupper())
print('Está escrito em minúsculo?', n.islower())
print('É um alfanumerico?',n.isalnum())
print('É decimal?',n.isdecimal())
print('É titulo?? ',n.istitle())